framux.route('averias',
           {template:'partials/averia-list.html',
controller:'AveriaList',
selector:'#content'})
.route('averia/:averiaId',
{template:'partials/averia-detail.html',
controller:'AveriaDetail',
selector:'#content'})
.route('averiaNew',
{template:'partials/averia-new.html',
controller:'AveriaNew',
selector:'#content'})
.route('averiaAdd',
{controller:'AveriaInsert',
selector:'#content'})
.route('averiaUpdate/:averiaId',
{controller:'AveriaUpdate',
selector:'#content'})
.route('averiaDelete/:averiaId',
{controller:'AveriaDelete',
selector:'#content'});
framux.go('averias');

framux.route('estadosaveria',
           {template:'partials/estadoaveria-list.html',
controller:'EstadoaveriaList',
selector:'#content'})
.route('estadoaveria/:estadoaveriaId',
{template:'partials/estadoaveria-detail.html',
controller:'EstadoaveriaDetail',
selector:'#content'})
.route('estadoaveriaNew',
{template:'partials/estadoaveria-new.html',
controller:'EstadoaveriaNew',
selector:'#content'})
.route('estadoaveriaAdd',
{controller:'EstadoaveriaInsert',
selector:'#content'})
.route('estadoaveriaUpdate/:estadoaveriaId',
{controller:'EstadoaveriaUpdate',
selector:'#content'})
.route('estadoaveriaDelete/:estadoaveriaId',
{controller:'EstadoaveriaDelete',
selector:'#content'});
framux.go('estadosaveria');

framux.route('tiposaveria',
           {template:'partials/tipoaveria-list.html',
controller:'TipoaveriaList',
selector:'#content'})
.route('tipoaveria/:tipoaveriaId',
{template:'partials/tipoaveria-detail.html',
controller:'TipoaveriaDetail',
selector:'#content'})
.route('tipoaveriaNew',
{template:'partials/tipoaveria-new.html',
controller:'TipoaveriaNew',
selector:'#content'})
.route('tipoaveriaAdd',
{controller:'TipoaveriaInsert',
selector:'#content'})
.route('tipoaveriaUpdate/:tipoaveriaId',
{controller:'TipoaveriaUpdate',
selector:'#content'})
.route('tipoaveriaDelete/:tipoaveriaId',
{controller:'TipoaveriaDelete',
selector:'#content'});
framux.go('tiposaveria');

framux.route('suscriptores',
           {template:'partials/suscriptor-list.html',
controller:'SuscriptorList',
selector:'#content'})
.route('suscriptor/:suscriptorId',
{template:'partials/suscriptor-detail.html',
controller:'SuscriptorDetail',
selector:'#content'})
.route('suscriptorNew',
{template:'partials/suscriptor-new.html',
controller:'SuscriptorNew',
selector:'#content'})
.route('suscriptorAdd',
{controller:'SuscriptorInsert',
selector:'#content'})
.route('suscriptorUpdate/:suscriptorId',
{controller:'SuscriptorUpdate',
selector:'#content'})
.route('suscriptorDelete/:suscriptorId',
{controller:'SuscriptorDelete',
selector:'#content'});
framux.go('suscriptores');

framux.route('sucursales',
           {template:'partials/sucursal-list.html',
controller:'SucursalList',
selector:'#content'})
.route('sucursal/:sucursalId',
{template:'partials/sucursal-detail.html',
controller:'SucursalDetail',
selector:'#content'})
.route('sucursalNew',
{template:'partials/sucursal-new.html',
controller:'SucursalNew',
selector:'#content'})
.route('sucursalAdd',
{controller:'SucursalInsert',
selector:'#content'})
.route('sucursalUpdate/:sucursalId',
{controller:'SucursalUpdate',
selector:'#content'})
.route('sucursalDelete/:sucursalId',
{controller:'SucursalDelete',
selector:'#content'});
framux.go('sucursales');

framux.route('regiones',
           {template:'partials/region-list.html',
controller:'RegionList',
selector:'#content'})
.route('region/:regionId',
{template:'partials/region-detail.html',
controller:'RegionDetail',
selector:'#content'})
.route('regionNew',
{template:'partials/region-new.html',
controller:'RegionNew',
selector:'#content'})
.route('regionAdd',
{controller:'RegionInsert',
selector:'#content'})
.route('regionUpdate/:regionId',
{controller:'RegionUpdate',
selector:'#content'})
.route('regionDelete/:regionId',
{controller:'RegionDelete',
selector:'#content'});
framux.go('regiones');

framux.route('cuadras',
           {template:'partials/cuadra-list.html',
controller:'CuadraList',
selector:'#content'})
.route('cuadra/:cuadraId',
{template:'partials/cuadra-detail.html',
controller:'CuadraDetail',
selector:'#content'})
.route('cuadraNew',
{template:'partials/cuadra-new.html',
controller:'CuadraNew',
selector:'#content'})
.route('cuadraAdd',
{controller:'CuadraInsert',
selector:'#content'})
.route('cuadraUpdate/:cuadraId',
{controller:'CuadraUpdate',
selector:'#content'})
.route('cuadraDelete/:cuadraId',
{controller:'CuadraDelete',
selector:'#content'});
framux.go('cuadras');

framux.route('tiposvivienda',
           {template:'partials/tipovivienda-list.html',
controller:'TipoviviendaList',
selector:'#content'})
.route('tipovivienda/:tipoviviendaId',
{template:'partials/tipovivienda-detail.html',
controller:'TipoviviendaDetail',
selector:'#content'})
.route('tipoviviendaNew',
{template:'partials/tipovivienda-new.html',
controller:'TipoviviendaNew',
selector:'#content'})
.route('tipoviviendaAdd',
{controller:'TipoviviendaInsert',
selector:'#content'})
.route('tipoviviendaUpdate/:tipoviviendaId',
{controller:'TipoviviendaUpdate',
selector:'#content'})
.route('tipoviviendaDelete/:tipoviviendaId',
{controller:'TipoviviendaDelete',
selector:'#content'});
framux.go('tiposvivienda');

framux.route('instalaciones',
           {template:'partials/instalacion-list.html',
controller:'InstalacionList',
selector:'#content'})
.route('instalacion/:instalacionId',
{template:'partials/instalacion-detail.html',
controller:'InstalacionDetail',
selector:'#content'})
.route('instalacionNew',
{template:'partials/instalacion-new.html',
controller:'InstalacionNew',
selector:'#content'})
.route('instalacionAdd',
{controller:'InstalacionInsert',
selector:'#content'})
.route('instalacionUpdate/:instalacionId',
{controller:'InstalacionUpdate',
selector:'#content'})
.route('instalacionDelete/:instalacionId',
{controller:'InstalacionDelete',
selector:'#content'});
framux.go('instalaciones');

framux.route('estadosserv',
           {template:'partials/estadoserv-list.html',
controller:'EstadoservList',
selector:'#content'})
.route('estadoserv/:estadoservId',
{template:'partials/estadoserv-detail.html',
controller:'EstadoservDetail',
selector:'#content'})
.route('estadoservNew',
{template:'partials/estadoserv-new.html',
controller:'EstadoservNew',
selector:'#content'})
.route('estadoservAdd',
{controller:'EstadoservInsert',
selector:'#content'})
.route('estadoservUpdate/:estadoservId',
{controller:'EstadoservUpdate',
selector:'#content'})
.route('estadoservDelete/:estadoservId',
{controller:'EstadoservDelete',
selector:'#content'});
framux.go('estadosserv');

framux.route('serviciosextra',
           {template:'partials/servicioextra-list.html',
controller:'ServicioextraList',
selector:'#content'})
.route('servicioextra/:servicioextraId',
{template:'partials/servicioextra-detail.html',
controller:'ServicioextraDetail',
selector:'#content'})
.route('servicioextraNew',
{template:'partials/servicioextra-new.html',
controller:'ServicioextraNew',
selector:'#content'})
.route('servicioextraAdd',
{controller:'ServicioextraInsert',
selector:'#content'})
.route('servicioextraUpdate/:servicioextraId',
{controller:'ServicioextraUpdate',
selector:'#content'})
.route('servicioextraDelete/:servicioextraId',
{controller:'ServicioextraDelete',
selector:'#content'});
framux.go('serviciosextra');

framux.route('servicios',
           {template:'partials/servicio-list.html',
controller:'ServicioList',
selector:'#content'})
.route('servicio/:servicioId',
{template:'partials/servicio-detail.html',
controller:'ServicioDetail',
selector:'#content'})
.route('servicioNew',
{template:'partials/servicio-new.html',
controller:'ServicioNew',
selector:'#content'})
.route('servicioAdd',
{controller:'ServicioInsert',
selector:'#content'})
.route('servicioUpdate/:servicioId',
{controller:'ServicioUpdate',
selector:'#content'})
.route('servicioDelete/:servicioId',
{controller:'ServicioDelete',
selector:'#content'});
framux.go('servicios');

